Hw04 lru cache
BashMS/hw_2425 pull request #4
Opened 2024-12-27 15:29 UTC by BashMS

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-12-27 17:00 UTC, vladislavmass requested changes

2024-12-27 17:00 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	if l.tail == nil {
Это условие выглядит как блок else к if в 49 строке

2024-12-27 17:00 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	if l.head == nil {
Это условие выглядит как блок else к if в 66 строке

2024-12-27 17:00 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +		l.head.Prev = nil
Подумайте что произойдет в этой строке если мы удаляем единственный элемент списка

2024-12-27 17:00 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	if l.size == 0 {
Хорошая идея, но рекомендую также подумать о том, зачем нам перемещать в начало элемент, который и так первый

2024-12-27 17:00 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +	var isExist bool
А зачем нам это переменная? Почему мы не можем вернуть нужное значение без присвоения?

2024-12-27 17:00 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +		isExist = true
Выглядит так как будто тут могло быть просто return true без else

2024-12-27 17:00 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +		item := l.queue.PushFront(tempCacheItem)
Капасити это размер кэша который мы не можем превышать. Данная же реализация подразумевает что в этот момент размер кэша может стать cap+1. Да потом мы удалим лишний элемент, но все равно капасити будет нарушен

2024-12-27 20:08 UTC, BashMS commented on hw04_lru_cache/list.go
> +	if l.tail == nil {
Объединил.

2024-12-27 20:08 UTC, BashMS commented on hw04_lru_cache/list.go
> +	if l.head == nil {
Объединил.

2024-12-27 20:08 UTC, BashMS commented on hw04_lru_cache/list.go
> +		l.head.Prev = nil
Обработал ситуацию, добавил тест.

2024-12-27 20:08 UTC, BashMS commented on hw04_lru_cache/list.go
> +	if l.size == 0 {
Исправил условие.

2024-12-27 20:09 UTC, BashMS commented on hw04_lru_cache/cache.go
> +	var isExist bool
Убрал. Изменил возврат результата.

2024-12-27 20:10 UTC, BashMS commented on hw04_lru_cache/cache.go
> +		isExist = true
Разбил if.

2024-12-27 20:10 UTC, BashMS commented on hw04_lru_cache/cache.go
> +		item := l.queue.PushFront(tempCacheItem)
Исправил.

2024-12-28 03:04 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +	var isExist bool
Не вижу никаких изменений

2024-12-28 03:06 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	if i == l.tail {
Если мы удаляем единственный элемент, то l.head мы затерли, но l.tail все еще указывает на этот элемент

2024-12-28 17:22 UTC, BashMS commented on hw04_lru_cache/cache.go
> +	var isExist bool
Пропустил Get, исправил.

2024-12-28 17:24 UTC, BashMS commented on hw04_lru_cache/list.go
> +	if i == l.tail {
Добавил исправление.

2024-12-28 18:27 UTC, vladislavmass approved these changes

2024-12-29 13:28 UTC, merged